### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by diegovargasf** [jmfernandes/robin_stocks#14]
Hi Joshua, 
Excellent work on this API wrapper, thank you for sharing! 

I seem to be getting the 404 Error for this call: get_option_market_data_by_id(id,info=None)

404 Client Error: Not Found for url: https://api.robinhood.com/marketdata/options/5a44c5fa-c6a8-4f91-a809-1e722c75051b/

I am sure of the id because I got it from the output of this call: get_available_option_calls(...)

Do you know what could be the issue? I am able to login and receive the token.

**Comment by jmfernandes** [comment]
I would suggest using functions like find_options_for_stock_by_expiration,get_available_option_calls, get_available_option_puts, or get_list_market_data, because these functions will also give you the market data, but the parameters are friendlier to use than passing in an ID. But if you wanted to use the get_option_market_data_by_id function, you would use it like this

    tslaID = r.helper.id_for_option('TSLA','2019-06-21',310,'call')
    stuff = r.get_option_market_data_by_id(tslaID)

keep in mind that you have to specify call or option for this ID, even though the function defaults to 'both'. For more info go here http://www.robin-stocks.com/en/latest/functions.html#getting-option-information

**Comment by jmfernandes** [comment]
found the issue. Robinhood added a new keyword to the data for rhs_tradability. Need to make sure that only only options where this is not set to "untradable" are passed into the get_option_market_data_by_id function. Will fix soon. in the function get_available_option_calls the payload should be

    payload = { 'chain_id' : r.helper.id_for_chain(symbol),
                'state' : 'active',
                'tradability' : 'tradable',
                'rhs_tradability': 'tradable',
                'type' : 'call'}

but for some reason that isn't correctly filtering the query. Still giving me rhs untradable options. The Robinhood API does this sometimes. I believe there are several endpoints that are supposed to be able to take an expiration date, but then it ignores it. To go around this, I'll just have to edit find_options_for_stock_by_expiration (and a few others) to be 

    for item in mergedList:
        if (item['rhs_tradability'] != 'untradable'):
            marketData = r.get_option_market_data_by_id(item['id'])
            print(marketData)
            item.update(marketData)

**Comment by jmfernandes** [comment]
Pushed the fix. Closing this issue. If any problems persist, open a new issue or you could help me out by fixing the issue and filling out a pull request. 👍
