### ISSUE TITLE
token = 'Bearer {}'.format(data['access_token'])

### ISSUE THREAD

**Issue by devintripp** [jmfernandes/robin_stocks#15]
this is the error I get every time I try and log in

**Comment by jmfernandes** [comment]
could you provide a little more detail? i'm able to login with both two factor authentication turned off and on.

**Comment by diegovargasf** [comment]
I have encountered this issue today. 

I have done some digging and it looks like the issue is happening in this line in authetication.py:
data = helper.request_post(url,payload)

The error that I'm seeing is: 
data = helper.request_post(url,payload)

this is the redacted payload, note that the password and username are working correctly in the robinhood app. 

challenge_type:sms
client_id:xxx
device_token:b34e3cf0-c549-8cef-2722-4f662bb12d96
expires_in:86400
grant_type:password
password:xxx
scope:internal
username:diego.vargas.frontanilla@xxx


I've seen this error before but it usually went away after restarting my python interpreter, however today, it is just not going away. I have even tried re installing robin_stocks.
