### ISSUE TITLE
order.py line 1442 

### ISSUE THREAD

**Issue by Victorwhatsup** [jmfernandes/robin_stocks#251]
has a bug in Crypto trading due to order.py line 1443

TypeError: order_crypto() missing 3 required positional arguments: 'symbol', 'side', and 'quantityOrPrice'

**Comment by ariadams1701** [comment]
I can confirm the issue. same error while attempting to buy by quantity.

**Comment by martian099** [comment]
I have the same issue as well. Problem is with order_crypto() function.

**Comment by maconard** [comment]
Ope, I also made a git issue for this: #254

**Comment by need12648430** [comment]
Can confirm. There are 2 functions named order_crypto, one contained in the urls module and one contained in the orders module. So urls.order_crypto gets overwritten by orders.order_crypto.

It can be easily fixed by importing and using the whole urls module, ensuring proper namespacing.

I patched it, but I'm unsure if the devs want to go about fixing it another way.

Should I submit a PR?

**Comment by jmfernandes** [comment]
fixed in 2.0.3
