### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by cosmo86** [jmfernandes/robin_stocks#26]
I am really sorry for posting this, i know there are a few posts regarding the same issue. but i am new to this and i really dont understand how you fix this problem. could someone give me some specific instructions to fixing this?
this is my code: my two factor authentication is off

import pandas as pd, numpy as np
import os
import time
import robin_stocks as r
import matplotlib.pyplot as plt
import datetime as dt

username='username@gmail.com'
password='*******'

login= r.login(username,password)

print ('done')

this is the error message:
400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/
Traceback (most recent call last):
File "C:\Users\HoneyMochi\Desktop\stock\stock 1.py", line 31, in 
login= r.login(username,password)
File "C:\Python37\lib\site-packages\robin_stocks\authentication.py", line 61, in login
token = 'Bearer {}'.format(data['access_token'])
TypeError: 'NoneType' object is not subscriptable

also , i get a text message that gives me a robinhood code everytime i run this script
so please, anyone, help me. i apologize again for the inconvenience.

**Comment by AmeliorateOr** [comment]
@cosmo86 take down your username and password. Someone can login with your credentials and with 2FA off, that is not going to help you any. I encourage you to immediately change your username and password now and never post it in future posts.

**Comment by cosmo86** [comment]
@AmeliorateOr  thanks man!, just updated the post and my account info. saved me!

**Comment by AmeliorateOr** [comment]
@cosmo86 
To answer your previous question, I'd suggest you try to look for this data outside of Robinhood. They've been trying to sequester access to their API for some time and it will become more difficult as time goes I imagine. 

I e-mailed Robinhood asking if they were planning on releasing a public API, and they replied suggesting that they had no intentions to do so, but that could change. Not very promising if you ask me. It appears they're looking to only partner with professional developer teams to create apps and the sort, but for personal use, you won't be able to get access I'm afraid. 

If you google search fast_arrow, there seems to be some sideways attempts that involve using an email and getting the 2FA code from the email and plugging it in, but it is quite the headache.

If you want to get involved with companies that do provide API access and have been around for a while, I'd suggest TDAmeritrade or InteractiveBrokers. Mind you, these are not for beginners, and are not free, but they have the data you're likely looking to get. TDAmeritrade you must have an account with them to get this information by creating a developer account and for Interactive Brokers I believe you need to open an account with $10,000 minimum (must be deposited initially, but can be taken down to some minimum, $2,000 I think??)... don't quote me on any of this as I'm just giving information I believe to be true but haven't tested. The one good thing about these companies however is they've been in the sector for quite some time so there is the very high likelihood that they're here to stay and keep these items available. Since Robinhood doesn't allow it, it's difficult for me to promote this way as it may not be as fruitful in the long-term. 

Either way, good luck!

**Comment by cosmo86** [comment]
@AmeliorateOr 
oh thank you so much!!! That is a very detailed answer. What i wish to accomplish is to get intraday data that way i can write some python script to analyze the data other than just reading the old moving average, MACD etc. I have tried google finance, yahoo*(they all stopped working) and since i have a account with Robinhood, i thought i might get data from them. but i guess this robin-stock doesnt work either  now? 
I also have an account with TDAmeritrade, but i definately dont have 10k there. 
I thought this kind of info would be available to the public under some fair trade law right? 
Anyway, thanks for the answer, if you have some ways to get the intraday data, definatly let me know. thanks a lot

**Comment by AmeliorateOr** [comment]
@cosmo86 
I don't believe TDAmeritrade has this $10k threshold, only Interactive Brokers.
For TDA you can start here if you have an account -> https://developer.tdameritrade.com/apis

Be sure to create a developer account, this is separate from your TDA account, but you must have a TDA account to be able to access the TDA developer API. A bit redundant, but it gets the job done. 

These are the types of API calls you can access once you've logged in and authenticated, some don't require authentication, but most do. 

Goodluck

**Comment by Wheaties466** [comment]
I pushed a commit that allows you to use 2FA. I don't think its been committed though.

**Comment by Jmarkaba** [comment]
Check out my comment on #24 . I think its better than using a 2FA workaround.

**Comment by jmfernandes** [comment]
closing. see #24
