### ISSUE TITLE
API giving lower portfolio numbers

### ISSUE THREAD

**Issue by taziamoma** [jmfernandes/robin_stocks#315]
Hi there, I've been using the Robinhood API to track my investments and portfolio value. But I've noticed that the Robinhood portfolio that my API gives me is usually around $1500 lower than what I see in my Robinhood app. Does anybody know why that is? Any fixes anybody knows?

**Comment by rickytan-AA** [comment]
Hi @taziamoma, I also had this issue and I discovered it was because I had equity in crypto that didn't add to the sum of my account portfolio number. This may be the case for you as well.

I used the `load_phoenix_account()` function under `robin_stocks.robinhood.account` to return unified portfolio information - this gave me the correct numbers as what I see on my phone app.

Hope this helps!
- Ricky

**Comment by taziamoma** [comment]
> Hi @taziamoma, I also had this issue and I discovered it was because I had equity in crypto that didn't add to the sum of my account portfolio number. This may be the case for you as well.
> 
> I used the `load_phoenix_account()` function under `robin_stocks.robinhood.account` to return unified portfolio information - this gave me the correct numbers as what I see on my phone app.
> 
> Hope this helps! - Ricky

This worked beautifully. Thank you so much. I'm posting my code for anybody who needs it in the future. 
```
acc = rs.account.load_phoenix_account()
portfolio = portfolio = acc['extended_hours_portfolio_equity']['amount']
```
