### ISSUE TITLE
updated this morning from 2.1.0 -> 3.0.4

### ISSUE THREAD

**Issue by Nllii** [jmfernandes/robin_stocks#399]
https://github.com/jmfernandes/robin_stocks/blame/9266c483b7ea66fb54e0208ddf9c5ee3e35f78f2/robin_stocks/robinhood/urls.py#L17

is this a new requirement variable? we have to pass the account number?
```bash
404 Client Error: Not Found for url: https://api.robinhood.com/accounts/account_number
400 Client Error: Bad Request for url: https://api.robinhood.com/portfolios/historicals/None/?interval=day&span=month&bounds=regular
```

**Comment by SingularityMan** [comment]
This is because load_account_profile needs to specify which information you're looking for.

If you go to the method that calls load_account_profile, you need to include info='account_number'. That way it will get the account number from your brokerage account.

Example:

`account_number = load_account_profile(info="account_number")`

That way it should include the account_number and you shouldn't have any issues.

**Comment by Nllii** [comment]
> This is because load_account_profile needs to specify which information you're looking for.
> 
> If you go to the method that calls load_account_profile, you need to include info='account_number'. That way it will get the account number from your brokerage account.
> 
> Example:
> 
> `account_number = load_account_profile(info="account_number")`
> 
> That way it should include the account_number and you shouldn't have any issues.

I am staying on version  2.1.0. I am not refactoring code.
