### ISSUE TITLE
Fractional Shares

### ISSUE THREAD

**Issue by taylerallen6** [jmfernandes/robin_stocks#72]
This is more of a question than an issue. As some of you are probably aware, Robinhood announced they will be offering fractional shares soon. Do you know if this will be supposed in the api?

**Comment by edwang2007** [comment]
interested in this as well

**Comment by jmfernandes** [comment]
Added

**Comment by luiscabreracuba99** [comment]
Hi i'm using the library to automatically buy any amounts of fractional shares. Ex: invest $100 in 100 stocks at $1 per share. In the algorithm i made a loop to buy one by one with a wait time between each cycle to give time robin-hood to filled the order. The problem is i'm getting most of the orders failed. Any help?. Thanks anyway the library is very useful

<img width="698" alt="Screen Shot 2020-06-18 at 11 07 13 AM" src="https://user-images.githubusercontent.com/64546384/85037986-0eafe880-b154-11ea-95b7-997390793dd3.png">
